name: build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [latest, branch@master]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: Build and install
        if: matrix.os == 'windows-latest'
        run: |
          xmake -rv
          xmake r
          xmake install --installdir=install-windows
          gci -path ./install-windows -recurse |
            compress-archive -destinationpath ./gruben-windows-amd64.zip

      - name: Build and install
        if: matrix.os == "ubuntu-latest"
        run: |
          xmake -rv
          xmake r
          xmake install --installdir=install-linux
          zip -r gruben-linux-amd64.zip install-linux/*


      # now publish a Release on GitHub:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            gruben-linux-amd64.zip
            gruben-windows-amd64.zip
            LICENSE.txt

